# Generated by Django 2.1.7 on 2023-04-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус животного',
                'verbose_name_plural': 'Статусы животного',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Местонахождение')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('creator_info', models.CharField(max_length=50, verbose_name='Контакты создателя')),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Animal')),
                ('animal_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.AnimalStatus')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус объявления',
                'verbose_name_plural': 'Статусы объявления',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(default='неизвестна', max_length=10, verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coloring', models.CharField(max_length=50, verbose_name='Окраска')),
            ],
            options={
                'verbose_name': 'Окрас',
                'verbose_name_plural': 'Окрасы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=10, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='Название вида')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='ann_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.AnnouncementStatus'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='coloring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Color'),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Gender'),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Photo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.Type'),
        ),
    ]
