# Generated by Django 2.1.7 on 2023-04-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пола'},
        ),
    ]
