# Generated by Django 2.1.7 on 2023-04-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0002_auto_20230413_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Полы'},
        ),
    ]
