# Generated by Django 3.2 on 2023-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0004_auto_20230413_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='extra_info',
            field=models.TextField(default='', verbose_name='Дополнительная информация'),
        ),
    ]
