# Generated by Django 3.2 on 2023-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0006_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='ann_status',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnnouncementStatus',
        ),
    ]
