# Generated by Django 3.2 on 2023-04-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0008_auto_20230427_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='coloring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.color', verbose_name='Окрас'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.type', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='animalstatus',
            name='animal_status',
            field=models.CharField(max_length=20, verbose_name='Статус животного'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_name',
            field=models.CharField(default='неизвестна', max_length=10, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ani_app.type', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender_name',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(verbose_name='Ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='Вид'),
        ),
    ]
